name: Zip Pack
on:
  push:
    branches:
      - main

jobs:
  zip-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Zip
        run: zip -r enchant-icons.zip . -x "*.git*" ".github/*" "README.md"
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: enchant-icons.zip
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
